title: Zhong Ruoyu
description: >-
  zhongruoyu.com
url: "https://zhongruoyu.com"
baseurl: "" # the subpath of the site, e.g. /blog

lang: en-SG
google_analytics: UA-167948296-2

permalink: /:categories/:year-:month/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
